spring.application.name=api

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_incidencias?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=clave_super_larga_para_firmar_tokens_jwt_de_gestion_incidencias_api_2026_con_mas_de_32_caracteres
jwt.expiration=86400000